apiVersion: v1
kind: Namespace
metadata:
  name: besom-start
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: git
  namespace: besom-start
spec:
  stack: dev
  branch: dev
  projectRepo: "https://github.com/alexstaeding/besom-start"
  workspaceTemplate:
    spec:
      podTemplate:
        spec:
          initContainers:
            - name: install-scala-cli-and-plugin
              image: debian:latest
              command:
                - "/bin/sh"
                - "-c"
              args:
                - |
                  apt-get update && apt-get install -y curl
                  curl -sSLf https://scala-cli.virtuslab.org/get | sh
                  curl -fsSL https://get.pulumi.com | sh
                  export PATH=$PATH:$HOME/.pulumi/bin
                  pulumi plugin install language scala 0.3.2 --server github://api.github.com/VirtusLab/besom
          containers: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: besom-start:default:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    namespace: besom-start
    name: default
